server:
  port: 8080

spring:
  application:
    name: springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PWD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
#    dynamic:
#      primary: queryDS
#      datasource:
#        queryDS:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#          username: ${MYSQL_USER_NAME}
#          password: ${MYSQL_USER_PWD}
#          type: com.zaxxer.hikari.HikariDataSource
#          hikari:
#            min-idle: 5
#            max-pool-size: 10
#            idle-timeout: 30000
#            pool-name: QueryPool
#            max-lifetime: 1800000
#            connection-timeout: 30000
#        crdDS:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#          username: ${MYSQL_USER_NAME2}
#          password: ${MYSQL_USER_PWD2}
#          type: com.zaxxer.hikari.HikariDataSource
#          hikari:
#            min-idle: 10
#            max-pool-size: 20
#            idle-timeout: 30000
#            pool-name: crdPool
#            max-lifetime: 1800000
#            connection-timeout: 30000

  #  jackson:
  #    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    ## 消费端配置
    concurrency: 1
    max-concurrency: 1
    acknowledge-mode: MANUAL

  redis:
    host: 127.0.0.1
    port: 6379 # Redis 服务器连接端口
    database: 0 # Redis 数据库索引（默认为 0）
#    password: # Redis 服务器连接密码（默认为空）
    timeout: 0 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
#    sentinel:
#      # 主节点的别名
#      master: mymaster
#      # sentinel服务的ip和端口
#      nodes: 49.232.135.248:16380,49.232.135.248:26380,49.232.135.248:36380

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
